version: '3'
services:
  frontend:
    container_name: weather-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
